site_name: Center for Computational Research
docs_dir: 'pages'
site_description: 'Center for Computational Research'
site_url: 'https://docs.ccr.buffalo.edu'
copyright: 'Copyright &copy; 2021 Center for Computational Research, University at Buffalo'
repo_name: 'ubccr/ccrdocs'
repo_url: 'https://github.com/ubccr/ccrdocs'
edit_uri: 'blob/main/pages'

theme:
  name: 'readthedocs'
  logo: 'images/logo.png'
  favicon: 'images/favicon.ico'
  include_homepage_in_sidebar: false

plugins:
  - search
  - awesome-pages
  - mkdocs-video

markdown_extensions:
  - toc:
      permalink: true
  - footnotes
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Accessing CCR Resources:
    - Getting Access: getting-access.md
    - Getting Started: getting-started.md
    - Two-Factor Authentication: 2fa.md
    - Frequently Asked Questions: faq.md
  - High Performance Computing:
    - Logging In: hpc/login.md
    - Node Types: hpc/node-types.md
    - Running jobs: hpc/jobs.md
    - Data Transfer: hpc/data-transfer.md
    - Storage: hpc/storage.md
  - Gateways & Portals:
    - CCR IDM (Identity Management Portal): portals/idm.md
    - ColdFront (Allocations Management Portal): portals/coldfront.md
    - Open OnDemand (Browser based HPC Portal): portals/ood.md
    - Open XDMoD (Job Metrics Portal): portals/metrics.md
    - WebMO (Chemistry Portal): portals/webmo.md
  - Software:
    - Software infrastructure: software/about.md
    - The Module System: software/modules.md
    - Building your own software: software/building.md
  - Cloud:
    - LakeEffect (On-Prem Cloud): cloud/lake-effect.md
    - Using the Cloud: cloud/using.md
    - Advanced Topics: cloud/advanced.md
  - Policies:
    - Accounts and Data Retention Policy: policies/accounts.md
    - Batch Scheduler Policy: policies/batch.md
    - Data Backup Policy: policies/backups.md
    - Data Ownership Policy: policies/data.md
    - Email Communications Policy: policies/email.md
    - Password Policy: policies/passwords.md
    - Permitted Use & Misuse of CCR: policies/misuse.md
    - Scratch Space Policy: policies/scratch.md
    - Software Installation Policy: policies/softwareinstall.md
    - Support Policy: policies/support.md
    - System Maintenance: policies/maintenance.md
